crowdfunding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('kitasabi/', include('home.urls')),
    path('kitasabi/', include('news.urls')),
    path('kitasabi/', include('programs.urls')),
    path('kitasabi/', include('forms.urls')),
    path('kitasabi/', include('userprofile.urls')),
    path('kitasabi/', include('about.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf import settings
from .views import *

app_name = 'home'

urlpatterns = [
    path('', index, name = 'index'),
    path('redirect-news', news, name = 'news' ),
    path('redirect-programs', programs, name= 'programs'),
    path('redirect-donate', donate, name = "donate"),
    path('redirect-signup', signup, name = "signup"),
    path('redirect-about', about, name='about'),
    path('admin/', admin.site.urls),
    
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
    # url(r'^$', home, name='home'),
]

userprofile/urls.py
from django.urls import path
from .views import *

app_name = 'userprofile'

urlpatterns = [
    path('userprofile/', userprofile, name = 'userprofile'),
    path('delete_donation/', del_donation, name = 'del_donation')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from forms.models import User

def index(req):
    if req.user.is_authenticated:
        try:
            user = User.objects.get(email = req.user.email)
        except:
            create_user_obj(req)

    return render(req, 'home/index.html',)

def news(req):
	return redirect('news/')
def programs(req):
	return redirect('programs/')
def donate(req):
	return redirect('donate/')
def signup(req):
    return redirect('signup/')	
def about(req):
    return redirect('about/')

# def logout(request):
#     request.session.flush()
# 	return render(request, 'index.html')

def create_user_obj(req):
    new_user = User()

    new_user.email = req.user.email
    new_user.name = req.user.username

    new_user.save()

home/templates/home/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <nav class="navbar navbar-expand-lg navbar-dark ">
    <a class="navbar-brand" href="{% url 'home:index' %}">KitaSabi.com</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:news' %}">News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:programs' %}">Programs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:about' %}">About</a>
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'userprofile:userprofile' %}">{{ user.get_full_name }}</a>
          {% else %}
          {% endif %}
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a href="{% url 'home:logout' %}"><button class="btn btn-outline-light border" type="button" style="border-radius: 20pt">Logout</button></a>
          {% else %}
          <a href="{% url 'home:social:begin' 'google-oauth2' %}"><button class="btn btn-outline-light border" type="button" style="border-radius: 20pt">Login</button></a>
        </li>
        {% endif %} 
      </ul>
    </div>
    
  </nav>
  </div>
    

home/templates/home/footer.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


    <div class="container">
      <div class="row py-3">
        <div class="col-md-9">
          <p class="text-white" style="opacity: 0.5">by SinarPerak</p>
        </div>
        <div class="col-md-3">
          <div class="d-inline-block">
            <div class="bg-circle-outline d-inline-block">
              <a href="https://www.facebook.com/" class="text-white" style="opacity: 0.5"><i class="fa fa-2x fa-fw fa-facebook"></i>
		</a>
            </div>

            <div class="bg-circle-outline d-inline-block">
              <a href="https://twitter.com/" class="text-white" style="opacity: 0.5">
                <i class="fa fa-2x fa-fw fa-twitter"></i></a>
            </div>

            <div class="bg-circle-outline d-inline-block">
              <a href="https://www.linkedin.com/company/" class="text-white" style="opacity: 0.5">
                <i class="fa fa-2x fa-fw fa-linkedin"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	 <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
	<title>KitaSabi</title>
</head>
	
<body>
	
	{% include 'home/base.html'%}

	<div class="container">
		<div class="row">
			<div class="col-sm-5" style = "text-align: center; ">
				<h1 class="first" align="center" style="margin-top: 25vh; color: white; font-size: 80px; font-family: montserrat">the world</h1>
				<h1 class="second" align="center" style="color:white; font-size: 80px; font-family: montserrat">needs <b><i>you.</i></b></h1>
				{% if user.is_authenticated %}
				<a href="{% url 'home:donate' %}"><button  class="btn btn-outline-light btn-lg" type="button" style="border-radius: 20pt">donate</button></a>
				{% else %}
				<a href="#" data-target="#login" data-toggle="modal"><button  class="btn btn-outline-light btn-lg login-trigger" type="button" style="border-radius: 20pt">donate</button></a>
			</div>
			{% endif %}
		</div>
	</div>
	<br><br><br><br><br><br>
	
	
	{% include 'home/footer.html'%}


	<!--Trigger-->

<div id="login" class="modal fade" role="dialog">
  <div class="modal-dialog">
    
    <div class="modal-content">
      <div class="modal-body">
        <button data-dismiss="modal" class="close">&times;</button>
        <h4 style="text-align: center">Want to donate? Login Now!</h4>
        <form>
				<a href="{% url 'home:social:begin' 'google-oauth2' %}"><button class="loginBtn loginBtn--google" type="button" style="margin-left: 150px; border-radius: 20pt">Login With Google</button></a>
         
        </form>
      </div>
    </div>
  </div>  
</div>
	


	
	
</body>
</html>

home/templates/home/layout.html
<!DOCTYPE html>
<html>
<head>
	<title>Google Signin Demo</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
		<div class="container">
				<a class="navbar-brand" href="/">Django App</a>
		</div>  
	</nav>
    <div class="container">
	    {% block content %}	
	    {% endblock content %}
    </div>
</body>
</html>