crowdfunding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('kitasabi/', include('home.urls')),
    path('kitasabi/', include('news.urls')),
    path('kitasabi/', include('programs.urls')),
    path('kitasabi/', include('forms.urls')),
    path('kitasabi/', include('userprofile.urls')),
    path('kitasabi/', include('about.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

forms/urls.py
from django.urls import path
from .views import *

app_name = 'forms'

urlpatterns = [
    path('redirect-home', index, name = 'index'),
    path('signup/', signup, name = 'signup'),
    path('donate/', donate, name = 'donate'),
    path('signup/after/', signup_after, name = 'signup_after'),
    path('donate/after/', donate_after, name = 'donate_after'),
]

home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf import settings
from .views import *

app_name = 'home'

urlpatterns = [
    path('', index, name = 'index'),
    path('redirect-news', news, name = 'news' ),
    path('redirect-programs', programs, name= 'programs'),
    path('redirect-donate', donate, name = "donate"),
    path('redirect-signup', signup, name = "signup"),
    path('redirect-about', about, name='about'),
    path('admin/', admin.site.urls),
    
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
    # url(r'^$', home, name='home'),
]

forms/models.py
from django.db import models
from programs.models import Program
import datetime
from django.utils.timezone import now

class Donation(models.Model):
    program_set = Program.objects.all()
    PROGRAM_CHOICES = ()

    for prog in program_set:
        new_prog = (prog, prog.title)
        PROGRAM_CHOICES = PROGRAM_CHOICES + (new_prog,)

    donor = models.CharField(max_length = 50)
    anon = models.BooleanField(default = False)
    donation = models.IntegerField(default = 0)
    email = models.EmailField(max_length = 50, default = "None")
    program = models.CharField(max_length = 300, default = "None")
    date_of_donation = models.DateTimeField(default = now, blank = True)

    def __str__(self):
        if self.anon or not self.donor:
            return 'Anonymous'
        return self.donor

class User(models.Model):
    name = models.CharField(max_length = 50)
    birthdate = models.DateField(default = datetime.date.today)
    email = models.EmailField(max_length = 50)
    password = models.CharField(max_length = 30)
    donation = models.ManyToManyField(Donation)

    def __str__(self):
        return self.name

forms/admin.py
from django.contrib import admin
from .models import *

admin.site.register(User)
admin.site.register(Donation)

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

forms/forms.py
from django import forms
from .models import Donation
from .models import User
from django.core.exceptions import ValidationError
import datetime

class SignUpForm(forms.Form):
    name = forms.CharField(label = "name", max_length = 50, widget = forms.TextInput(
        attrs = {
            'class': 'form-attr',
            'placeholder': 'your name',
            'required': True,
        }
    ))

    birthdate = forms.DateField(label = "birth date", widget = forms.DateInput(
        attrs = {
            'class': 'form-attr',
            'required': True,
            'placeholder': 'mm/dd/yyyy'
        }
    ))

    email = forms.EmailField(label = "e-mail", widget = forms.EmailInput(
        attrs = {
            'class': 'form-attr',
            'required': True,
            'placeholder': 'name@email.com',
        }
    ))

    password = forms.CharField(label = "password", widget = forms.PasswordInput(
        attrs = {
            'class': 'form-attr',
            'required': True,
            'placeholder': 'password',
        }
    ))

class DonationForm(forms.Form):
    donor = forms.CharField(label = "name", required = False, max_length = 50, widget = forms.TextInput(
        attrs = {
            'class': 'form-attr',
            'placeholder': 'your name',
            'required': False,
        }
    ))

    email = forms.EmailField(label = "e-mail", required = False, widget = forms.EmailInput(
        attrs = {
            'class': 'form-attr',
            'required': False,
            'placeholder': 'name@email.com',
        }
    ))

    program = forms.ChoiceField(required = False, label = "program", choices = Donation.PROGRAM_CHOICES, widget = forms.Select(
        attrs = {
            'class': 'form-attr',
            'required': False,
            'placeholder': 'choose a program',
        }
    ))

    donation = forms.IntegerField(label = "amount", widget = forms.NumberInput(
        attrs = {
            'class': 'form-attr',
            'required': True,
            'placeholder': 'amount to donate',
        }
    ))

    anon = forms.BooleanField(label = "", required = False, widget = forms.CheckboxInput(
        attrs = {
            'class': 'styled-checkbox', 
            'required': False,}
    ))

    def clean_email(self):
        email = self.cleaned_data['email']

        if not User.objects.filter(email = email).first():
            raise forms.ValidationError('Email anda belum terdaftar. Silahkan login terlebih dahulu.')
        return email

forms/tests.py
from django.test import TestCase, Client
from django.urls import resolve
from .forms import *
from .views import *
from .models import *
import datetime

class SignUpFormUnitTest(TestCase):
    def test_url_is_exist(self):
        response = Client().get('/kitasabi/signup/')
        self.assertEqual(response.status_code, 200)

    def test_using_signup_func(self):
        found = resolve('/kitasabi/signup/')
        self.assertEqual(found.func, signup)

    def test_using_proper_template(self):
        response = Client().get('/kitasabi/signup/')
        self.assertTemplateUsed(response, 'forms/signup.html')

    def test_signup_returns_proper_responses(self):
        response = Client().get('/kitasabi/signup/')
        self.assertIn('form', response.context)

    def test_signup_can_save_POST_req(self):
        signup_data = { 'name':'NAME',
                        'birthdate': '10/25/2006',
                        'email': 'josh.sudung07@gmail.com',
                        'password':'12345' }

        response = Client().post('/kitasabi/signup/', signup_data)
        obj_count = User.objects.all().count()
        self.assertEqual(obj_count, 1)

        first_obj = User.objects.first()
        self.assertEqual(str(first_obj), 'NAME')
        

class DonationFormUnitTest(TestCase):
    def test_url_is_exist(self):
        response = Client().get('/kitasabi/donate/')
        self.assertEqual(response.status_code, 200)

    def test_using_donate_func(self):
        found = resolve('/kitasabi/donate/')
        self.assertEqual(found.func, donate)

    def test_using_proper_template(self):
        response = Client().get('/kitasabi/donate/')
        self.assertTemplateUsed(response, 'forms/donate.html')

    def test_donate_returns_proper_responses(self):
        response = Client().get('/kitasabi/donate/')
        self.assertIn('form', response.context)

class AfterFormUnitTest(TestCase):
    def test_signup_after_url_is_exist(self):
        response = Client().get('/kitasabi/signup/after/')
        self.assertEqual(response.status_code, 200)

    def test_using_signup_after_func(self):
        found = resolve('/kitasabi/signup/after/')
        self.assertEqual(found.func, signup_after)

    def test_using_proper_signup_after_template(self):
        response = Client().get('/kitasabi/signup/after/')
        self.assertTemplateUsed(response, 'forms/signup_after.html')

    def test_donate_after_url_is_exist(self):
        response = Client().get('/kitasabi/donate/after/')
        self.assertEqual(response.status_code, 200)

    def test_using_donate_after_func(self):
        found = resolve('/kitasabi/donate/after/')
        self.assertEqual(found.func, donate_after)

    def test_using_proper_donate_after_template(self):
        response = Client().get('/kitasabi/donate/after/')
        self.assertTemplateUsed(response, 'forms/donate_after.html')

class RedirectHomeUnitTest(TestCase):
    def test_redirect_home_url_is_exist(self):
        response = Client().get('/kitasabi/redirect-home')
        self.assertEqual(response.status_code, 302)

    def test_using_index_func(self):
        found = resolve('/kitasabi/redirect-home')
        self.assertEqual(found.func, index)

class FormModelsUnitTest(TestCase):
    def test_add_obj_to_user_model(self):
        User.objects.create()

        obj_count = User.objects.all().count()
        self.assertEqual(obj_count, 1)

    def test_add_obj_to_donation_model(self):
        Donation.objects.create()

        obj_count = Donation.objects.all().count()
        self.assertEqual(obj_count, 1)

class FormsUnitTest(TestCase):
    def test_signup_form_valid_to_model(self):
        signup_data = { 'name':'NAME',
                        'birthdate': '10/25/2006',
                        'email': 'josh.sudung07@gmail.com',
                        'password':'12345' }
        signup_form = SignUpForm(signup_data)
        self.assertTrue(signup_form.is_valid())

        user_obj = User()
        user_obj.name = signup_form.cleaned_data['name']
        user_obj.save()
        self.assertEqual(str(user_obj), 'NAME')
        self.assertEqual(User.objects.all().count(), 1)

forms/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
from .models import *

def index(req):
    return redirect('/')

def signup(req):
    if req.method == 'POST':
        form = SignUpForm(req.POST)
        if form.is_valid():
            new_user = User()
            new_user.name = form.cleaned_data['name']
            new_user.birthdate = form.cleaned_data['birthdate']
            new_user.email = form.cleaned_data['email']
            new_user.password = form.cleaned_data['password']
            new_user.save()
        return redirect('forms:signup_after')
    else:
        form = SignUpForm()
        return render(req, 'forms/signup.html', {'form': form})

def donate(req):
    if req.method == 'POST':
        form = DonationForm(req.POST)
        if form.is_valid():
            new_donation = Donation()
            new_donation.donor = req.user.first_name + " " + req.user.last_name
            new_donation.anon = form.cleaned_data['anon']
            new_donation.email = req.user.email
            new_donation.donation = form.cleaned_data['donation']
            new_donation.program = form.cleaned_data['program']
            new_donation.save()

            current_user = User.objects.get(email = req.user.email)

            current_user.donation.add(new_donation)

            return redirect('forms:donate_after')
        else:
            return render(req, 'forms/donate.html', {'form': form})
    else:
        form = DonationForm()
        return render(req, 'forms/donate.html', {'form': form})


def signup_after(req):
    return render(req, 'forms/signup_after.html',)

def donate_after(req):
    return render(req, 'forms/donate_after.html',)

forms/templates/forms/donate.html
<!doctype html>
{% load static %}
<html lang="en-US">
<html>
    <head>
        <title>Donation</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <!-- <link rel = "stylesheet" href = "{% static 'crowdfunding/global.css' %}"> -->
    </head>
    <body>
        
        {% include 'home/base.html' %}
        <div class = "container">
            <div class = "content center-elements">
                <div class = "card signup-card white-text">
                    <h1 class = "giant-text">donate</h1>
                    <div>
                        <form class = "control" method="POST" action="{% url 'forms:donate' %}">
                            {% csrf_token %}
                            {{ form.program.label_tag }}
                            {{ form.program }}
                            {{ form.donation.label_tag }}
                            {{ form.donation }}
                            {{ form.anon }}<span class = "hide-donor">&nbsp hide my name as donor</span>
                            <div class = "center">
                                <input class = "signup-button white-text btn btn-sm" type = "submit" value = "donate">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <link rel = "stylesheet" href = "{% static 'forms/style.css' %}">
    </body>
</html>

forms/templates/forms/donate_after.html
<!doctype html>
{% load static %}
<html lang="en-US">
<html>
    <head>
        <title>Thanks!</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel = "stylesheet" href = "{% static 'crowdfunding/global.css' %}">
        <link rel = "stylesheet" href = "{% static 'forms/style.css' %}">
    </head>
    <body>
        {% include 'home/base.html' %}
        <div class = "container">
            <div class = "content center-elements">
                <div class = "white-text center-1">
                    <h1 class = "giant-text">thankyou</h1>
                    <h1>that means a lot</h1>
                    <a href = "{% url 'forms:index' %}"><button class = "redirect-button white-text">back to home</button></a>
                </div>
            </div>
        {% include 'home/footer.html' %}
        </div>

    </body>
</html>

forms/templates/forms/signup.html
<!doctype html>
{% load static %}
<html lang="en-US">
<html>
    <head>
        <title>Sign Up</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel = "stylesheet" href = "{% static 'crowdfunding/global.css' %}">
        <link rel = "stylesheet" href = "{% static 'forms/style.css' %}">
    </head>
    <body>
        {% include 'home/base.html' %}
        <div class = "container">
            <div class = "content center-elements">
                <div class = "card signup-card white-text">
                    <h1 class = "giant-text">regist</h1>
                    <div>
                        <form class = "control" method="POST" action="{% url 'forms:signup' %}">
                            {% csrf_token %}
                            {{ form }}
                            <div class = "center">
                                <input class = "signup-button white-text btn btn-sm" type = "submit" value = "sign up">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

forms/templates/forms/signup_after.html
<!doctype html>
{% load static %}
<html lang="en-US">
<html>
    <head>
        <title>Thanks!</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel = "stylesheet" href = "{% static 'crowdfunding/global.css' %}">
        <link rel = "stylesheet" href = "{% static 'forms/style.css' %}">
    </head>
    <body>
        {% include 'home/base.html' %}
        <div class = "container">
            <div class = "content center-elements">
                <div class = "white-text center-1">
                    <h1 class = "giant-text">thankyou</h1>
                    <h1>so glad having you here</h1>
                    <a href = "{% url 'forms:donate' %}"><button class = "redirect-button white-text" id = "mr-donate">donate</button></a>
                    <a href = "{% url 'forms:index' %}"><button class = "redirect-button white-text">back to home</button></a>
                </div>
            </div>
        {% include 'home/footer.html' %}
        </div>
    </body>
</html>